# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [3]:
# Your code here
A = np.random.randint(0, 11, size=(2, 4))
B = np.random.randint(0, 20, size=(4, 5))
C = np.random.randint(0, 15, size=(4, 5))
print('A\n', A, '\n')
print('B\n', B, '\n')
print('C\n', C, '\n')

A
 [[ 2  2 10  8]
 [ 6  3  7  8]] 

B
 [[ 6  8  2 11 15]
 [18 10 14  3 16]
 [ 6 10 10 13  3]
 [ 5  4  3 19  2]] 

C
 [[ 7  7  3  8  8]
 [ 3 14  6 14  9]
 [ 1  1 11  2  8]
 [ 7  9  0  2 10]] 



In [5]:
A.dot(B + C) == (A.dot(B) + A.dot(C))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
print(A.dot(B + C))
print(A.dot(B) + A.dot(C))

[[234 292 284 390 302]
 [286 343 261 438 386]]
[[234 292 284 390 302]
 [286 343 261 438 386]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [8]:
# Your code here 
A = np.random.randint(0, 11, size=(2, 4))
B = np.random.randint(0, 20, size=(4, 5))
C = np.random.randint(0, 15, size=(5, 2))
print('A\n', A, '\n')
print('B\n', B, '\n')
print('C\n', C, '\n')

A
 [[ 5  8  1 10]
 [ 8  8  8  9]] 

B
 [[ 7  4 17 17 13]
 [ 8 19  5  9  8]
 [15  9  5  5 14]
 [18  2 17 12 13]] 

C
 [[ 3  4]
 [ 0 14]
 [ 9 10]
 [11  8]
 [ 8  7]] 



In [10]:
A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True,  True],
       [ True,  True]])

In [11]:
print(A.dot(B.dot(C)))
print(A.dot(B).dot(C))

[[ 8868 11157]
 [11619 14761]]
[[ 8868 11157]
 [11619 14761]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [12]:
# Your code here 
A = np.random.randint(0, 11, size=(2, 4))
B = np.random.randint(0, 20, size=(4, 5))

print('A\n', A, '\n')
print('B\n', B, '\n')

A
 [[ 9  0  5  1]
 [ 5  7  4 10]] 

B
 [[ 5 10  5  7 19]
 [ 7  5  5  6 14]
 [ 4  1  0 10 18]
 [ 8 16  5  1  9]] 



In [13]:
A.dot(B) != B.dot(A)

ValueError: shapes (4,5) and (2,4) not aligned: 5 (dim 1) != 2 (dim 0)

In [23]:
print(A.dot(B))
print(B.dot(A))

[[ 73 111  50 114 270]
 [170 249 110 127 355]]


ValueError: shapes (4,5) and (2,4) not aligned: 5 (dim 1) != 2 (dim 0)

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [20]:
# Your code here 
x = np.random.randint(15, size=(4))
y = np.random.randint(15, size=(4))

print('x\n', x, '\n')
print('y\n', y, '\n')

x
 [12 11  5  1] 

y
 [8 3 9 8] 



In [22]:
np.transpose(x).dot(y) == np.transpose(y).dot(x)

True

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [26]:
# Your code here 
A = np.random.randint(0, 11, size=(2, 4))
B = np.random.randint(0, 20, size=(4, 5))

print('A\n', A, '\n')
print('B\n', B, '\n')

A
 [[ 3  4  0  8]
 [ 9  2 10  5]] 

B
 [[17  5  4 11  4]
 [ 8  9  4  2  1]
 [12  1 11 15  9]
 [16 14  1 19 18]] 



In [27]:
np.transpose(A.dot(B)) == np.transpose(B).dot(np.transpose(A))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [28]:
print(np.transpose(A.dot(B)))
print(np.transpose(B).dot(np.transpose(A)))

[[211 369]
 [163 143]
 [ 36 159]
 [193 348]
 [160 218]]
[[211 369]
 [163 143]
 [ 36 159]
 [193 348]
 [160 218]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 